# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93ea880a4c474d830c19b1d9aa1ae13fb5f4051071b64c02a6028920dd477990e080b552bdc4ee12398a4ae22e36f2d989580a8618698c427f5d2b06f1fd2b2e

test:
  secret_key_base: 5bfdcba65ccddd39493e6289749b61f9274ffcc7f9592e06589884e0a661c5916e27734de5cdc8172ee6116ccbbde96b66c2edefbba12250425a5f5f3cc0bbf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
